I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 100, in script call
    call sissignora from _call_sissignora
  File "game/script.rpy", line 222, in script
    $ l = len(domande)
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 100, in script call
    call sissignora from _call_sissignora
  File "game/script.rpy", line 222, in script
    $ l = len(domande)
  File "C:\Users\david\Downloads\Programs\renpy-8.0.2-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.2.22081402
Welcome to Hinamizawa 3.0
Thu Sep  8 20:47:50 2022
